# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e760e80ea0cc0b243836cb0f6096f55bcfabe79ac0b41e9bd877b86552e20223487dc3e60c3b90c74cb286ea86f675d11277e0516f3212daa3767d3e9074af74

test:
  secret_key_base: cf872c1d4c6e0c541775869c423c3fe57f10036c55d040056f515c401c246dde79b1ff44720d301f98501cee25e8d1feff0c5d48d6368971f88b5a75d1a87383

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
